version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - app1
      - app2
    networks:
      - app-network

  app1:
    build: ./backend
    container_name: app1
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/notepad
      - SPRING_REDIS_HOST=redis
    depends_on:
      - db
      - redis
    networks:
      - app-network

  app2:
    build: ./backend
    container_name: app2
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/notepad
      - SPRING_REDIS_HOST=redis
    depends_on:
      - db
      - redis
    networks:
      - app-network

  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_DB: notepad
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - app-network

  redis:
    image: redis:latest
    container_name: redis_cache
    ports:
      - "6379:6379"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
